FROM registry.cn-hangzhou.aliyuncs.com/itxishu/agi:v1

# Set up time zone.
ENV TZ=UTC
RUN sudo ln -snf /usr/share/zoneinfo/$TZ /etc/localtime
# WORKDIR 指定工作目录
WORKDIR /home/

# 安装包
COPY . .
RUN pip install -r requirements.txt

# MAINTAINER
MAINTAINER starkwang starkwanglab@gmail.com

ENV DEBIAN_FRONTEND noninteractive


# EXPOSE 暴露 80 端口
EXPOSE 80
EXPOSE 8080



# CMD ["python3", "openai-api.py"]
